spine-tools/spine-items

spine_items/data_connection/custom_file_system_watcher.py, spine_items/data_connection/data_connection.py, spine_items/data_connection/widgets/data_connection_properties_widget.py, spine_items/tool/widgets/tool_specification_editor_window.py, tests/data_connection/test_DataConnection.py
Previously we were renaming and removing Data connection's file references automatically bypassing the undo stack which led to situation where the file system watcher could modify the project but user couldn't undo, redo or even save the changes.
We now just mark deleted or renamed file references as "missing". This gives the user a proper heads-up that something is wrong and an option to e.g. refresh the references.
This also enables us to work around the disappearing Excel (and other software) files in a nice way: in case a file is renamed, we mark it as missing, but we automatically try to refresh the reference after 1s.
Fixes Spine-project/Spine-Toolbox#1691
=> Change how DC handles reference deletion and renaming

bin/append_license.py, bin/build_ui.py, bin/update_copyrights.py
Fixes the `build_ui` script that still used the ole copyright years 2017-2021.
Re Spine-project/Spine-Toolbox#1820
=> Update copyright years in build_ui script

spine_items/exporter/exporter.py, spine_items/exporter/mvcmodels/mapping_editor_table_model.py, spine_items/exporter/mvcmodels/preview_tree_model.py, spine_items/gdx_exporter/widgets/parameter_index_settings_window.py, spine_items/tool/widgets/tool_specification_editor_window.py
No functional changes intended. Attribute and item getter provide slightly better performance over lambda.
Re Spine-project/Spine-Toolbox#1854
=> Use attribute and item getters as sort keys

tests/mock_helpers.py, tests/tool/widgets/test_toolSpecificationEditorWindow.py
- The removed functions in mock_helpers.py were duplicates of the ones in spine toolbox tests. Removed these to minimize confusion.
- Commented some tests that were skipped as obsolete to prevent uninformative logging
No related issue.
=> Remove duplicate test functions and adapt tests for this

spine_items/data_connection/data_connection.py
Data Connection's Duplicate and duplicate files does not do what it promises. The data files are not copied to the duplicated item's data dir as they should. This PR fixes the problem.
Fixes Spine-project/Spine-Toolbox#1233
=> Fix 'Duplicate and duplicate files' Context-menu item for Data Connections

spine_items/data_transformer/executable_item.py, spine_items/db_writer_executable_item_base.py, spine_items/exporter/executable_item.py, spine_items/exporter_executable_item_base.py, spine_items/gdx_exporter/executable_item.py, spine_items/gimlet/executable_item.py, spine_items/importer/do_work.py, spine_items/importer/executable_item.py, spine_items/merger/do_work.py, spine_items/merger/executable_item.py, spine_items/tool/executable_item.py, tests/data_connection/test_DataConnection.py, tests/data_connection/test_DataConnectionExecutable.py, tests/data_store/test_DataStoreExecutable.py, tests/data_transformer/test_DataTransformerExecutable.py, tests/gdx_exporter/test_GdxExporterExecutable.py, tests/gimlet/test_GimletExecutable.py, tests/importer/test_ImporterExecutable.py, tests/merger/test_MergerExecutable.py, tests/tool/test_ToolExecutable.py, tests/view/test_ViewExecutable.py
Importer and Merger now utilize a shared to lock that prevents them from importing data into the same database at the same time.
Note the accompanying PR Spine-project/spine-engine#72
Fixes irena-flextool/flextool#30
~- [ ] Unit tests pass~ Won't pass due to changes in Spine Engine and executable item base class.
=> Fix parallel Importers and Mergers

spine_items/data_store/data_store.py, tests/data_store/test_dataStore.py
Data Store now ensures the .sqlite file exists before the URL resource is broadcast. This prevents connections from failing to read scenarios/tools for filtering.
Fixes Spine-project/Spine-Toolbox#1925
=> Ensure that Data Store creates a new sqlite file before it is advertised

spine_items/exporter/commands.py, spine_items/exporter/mvcmodels/mapping_editor_table_model.py, spine_items/exporter/widgets/specification_editor_window.py, tests/data_connection/test_DataConnection.py, tests/exporter/mvcmodels/test_mapping_editor_table_model.py, tests/exporter/widgets/__init__.py, tests/exporter/widgets/test_specification_editor_window.py, tests/importer/mvcmodels/test_SourceDataTableModel.py, tests/mock_helpers.py
Setting any mapping as "table name" now disables the Fixed table name check box and the name text edit. Also, setting another mapping as "table name" removes other "table name" positions.
Fixes spine-tools/Spine-Toolbox#1792
=> Prevent multiple table names in Exporter

spine_items/data_transformer/filter_config_path.py
Fixes spine-tools/Spine-Toolbox#1867
=> Prepend Data Transformer's private config file name by '.'

spine_items/importer/widgets/options_widget.py
Fixed check boxes that got broken with the transition to PySide6.
Inspired by spine-tools/Spine-Toolbox#1024
=> Fix check boxes in Importer's Source options

spine_items/importer/widgets/import_sources.py, tests/importer/widgets/test_import_sources.py
This fixes a bug where we bailed out from updating the source data table when there was no data even if there was a valid header.
Fixes spine-tools/Spine-Toolbox#1024
=> Fix header only source data tables in Importer

spine_items/exporter/do_work.py
The link provided to the written files was broken in certain corner cases.
Fixes spine-tools/Spine-Toolbox#1944
=> Fix link in exporter's execution logs

spine_items/exporter/widgets/specification_editor_window.py, tests/exporter/widgets/test_specification_editor_window.py
The duplicate specification was referencing the original one linking the specifications in surprising and project breaking ways.
Fixes spine-tools/Spine-Toolbox#1955
=> Fix specifciation duplication in Exporter

spine_items/exporter/widgets/preview_updater.py, tests/exporter/widgets/test_preview_updater.py
This fixes a Traceback that happened when Exporter specification editor was closed after the Exporter item was removed from the project.
Fixes spine-tools/Spine-Toolbox#1870
=> Fix Traceback when closing Exporter specification editor

.github/workflows/run_unit_tests.yml
Installation of the `unixodbc-dev` package is currently broken on Linux. Luckily, it's not needed.
Re spine-tools/Spine-Toolbox#1979
=> Fix GitHub actions

spine_items/exporter/specification.py, spine_items/exporter/widgets/specification_editor_window.py, spine_items/importer/flattened_mappings.py
This PR makes it impossible to create object group mappings (import or export) with parameter components.
Resolves spine-tools/Spine-Toolbox#1324
=> Disable parameter components from object group mappings

spine_items/data_connection/output_resources.py, tests/data_connection/test_output_resources.py
Data connection now provides generic URLs instead of Spine database resources so other items don't try to treat them as Spine databases.
Fixes spine-tools/Spine-Toolbox#2018
=> Replace database resources by URL resources in Data connection

spine_items/tool/executable_item.py, spine_items/tool/tool.py, spine_items/tool/tool_specifications.py, spine_items/tool/ui/tool_specification_form.py, spine_items/tool/ui/tool_specification_form.ui, spine_items/tool/widgets/tool_specification_editor_window.py, tests/tool/test_Tool.py, tests/tool/test_ToolExecutable.py, tests/tool/test_tool_instance.py, tests/tool/test_tool_specifications.py
This PR removes all references to **Tool Specs'** 'execute_in_work' setting, and the 'Execute in work' check box in Tool Specification Editor.
Re spine-tools/Spine-Toolbox#884
=> Make execute in work a Tool setting only

spine_items/tool/commands.py, spine_items/tool/executable_item.py, spine_items/tool/tool.py, spine_items/tool/tool_instance.py, spine_items/tool/tool_specifications.py, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, tests/tool/test_ToolExecutable.py, tests/tool/test_tool_instance.py
This adds an option to Tool that allows killing persistent Julia and Python consoles when execution finishes.
Re spine-tools/Spine-Toolbox#1586
=> Add option to Tool to kill executed console processes

spine_items/data_store/data_store.py
Error handling is currently done by emitting the errors where they happen. If it is a benign/expected error, the logger is set to `None` to suppress the output. This poses problems when a function could both raise benign and real errors, as in spine-tools/Spine-Toolbox#2014 . This patch fixes the issue locally, but a more robust error handling would be beneficial in the long term, see spine-tools/Spine-Toolbox#2041 .
No documentation needs to be updated.
Code changes are checked with `black`.
Unit tests pass.
Fixes spine-tools/Spine-Toolbox#2014
=> split actions by dialect type

spine_items/importer/mvcmodels/mappings_model.py, spine_items/importer/widgets/import_editor_window.py, spine_items/importer/widgets/import_mappings.py, spine_items/importer/widgets/import_sources.py, tests/data_store/test_dataStore.py, tests/importer/mvcmodels/test_mappings_model.py, tests/importer/widgets/test_import_sources.py
This PR improves the visuals of Importer specification editor's Source tables list. Most importantly, we don't hide tables that are in the specification but don't exist in the source. Instead, the tables are grayed out with a tooltip explaining the situation. Also, tables that have been found in the source but do not yet have entries in the specification get a '(new)' token appended to their names. This will hopefully make it easier to spot mappings that need attention when the source changes.
Fixes spine-tools/Spine-Toolbox#1608
=> Don't hide Importer's source tables

spine_items/data_store/data_store.py, tests/data_store/test_dataStore.py
Data store doesn't advertise its resources if the URL is invalid. If user fixes the URL, Data store should advertise the fixed URL as a new resource, not as replacement to an old one (which was never broadcast to other items).
Fixes spine-tools/Spine-Toolbox#2060
=> Fix resource advertisement in Data store

spine_items/importer/widgets/import_editor_window.py
Adds a `*.*` selection option when selecting file to import, as per https://github.com/spine-tools/Spine-Toolbox/issues/2039#issuecomment-1514149925.
Fixes spine-tools/Spine-Toolbox#2039
=> Add a *.* file selection option to Importer

spine_items/importer/widgets/options_widget.py, tests/importer/widgets/test_OptionsWidget.py
This fixes the duplicate options in Importer's Source options dock.
Fixes spine-tools/Spine-Toolbox#2106
=> Fix Importer's Source options widget

spine_items/importer/widgets/import_mappings.py
The Add button is now active always except when the Select All -option is selected. The Remove and Duplicate buttons now activate and deactivate depending on whether there are any mappings in the selected source table.
Fixes spine-tools/Spine-Toolbox#2046
=> Fix importer specification editors mappings buttons

spine_items/tool/widgets/tool_specification_editor_window.py
In the tool specification editor the main program file and every additional program file now shows the whole file path in tooltips.
Fixes spine-tools/Spine-Toolbox#1745
=> Fix program filepath tooltips in Tool Spec Editor

spine_items/exporter/widgets/preview_updater.py
We had to downgrade Black due to dependency conflicts.
Re spine-tools/Spine-Toolbox#2115
=> Black formatting

spine_items/exporter/mvcmodels/mapping_editor_table_model.py, spine_items/exporter/mvcmodels/mappings_table_model.py
Relationship object highlighting mappings have changed in `spinedb_api` and this PR brings `spine_items` up-to-date.
See spine-tools/Spine-Database-API#246
Fixes spine-tools/Spine-Database-API#244
=> Update exporter according to mapping changes in spinedb_api

requirements.txt, spine_items/data_transformer/widgets/specification_editor_window.py, spine_items/exporter/widgets/specification_editor_window.py, spine_items/importer/widgets/import_editor_window.py, spine_items/tool/widgets/tool_specification_editor_window.py
When trying to exit an items specification editor without naming the specification, users are now asked if they want to exit without saving or cancel the exit. For the Tool item the same applies when tool type or main program file is not selected.
Fixes spine-tools/Spine-Toolbox#2123
=> Fix Cannot exit from specification editor without naming

spine_items/tool/executable_item.py
See title.
Fixes spine-tools/Spine-Toolbox#2132
=> Remove unnecessary Tool messages from Event Log

spine_items/tool/widgets/tool_specification_editor_window.py
The tool spec editor no longer can have the same file as the main program file as well as an additional program file. If the user tries to add a file that is already loaded into the tool spec editor, the file will be skipped and a popup alerting of this will be shown.
Fixes spine-tools/Spine-Toolbox#2128
=> Issue 2128 tool spec editor duplicate files

spine_items/merger/merger.py
Merger now recognizes Data Transformers as valid inputs.
Fixes spine-tools/Spine-Toolbox#2131
=> Fix Data Transformer valid input for merger

spine_items/importer/mvcmodels/mappings_model.py, spine_items/importer/widgets/import_mappings.py
Further improves implementation related to spine-tools/Spine-Toolbox#2046:
This also disables the 'add' button when selecting the 'rename this to add' entry. As part of that rewrite, a bunch of code could be removed again.
=> importer mappings button improvement

spine_items/importer/widgets/import_mappings.py
Fixed a bug where when importer spec editor was opened in anonymous mode, the add, remove and duplicate buttons were initially enabled. Also fixed a bug that duplicating a mapping sometimes disabled the add button.
Re spine-tools\Spine-Toolbox#2046
=> fix importer mappings buttons in anonymous mode

requirements.txt, spine_items/tool/widgets/tool_specification_editor_window.py
If the spec editor of a tool that has no specification is opened, the text editor widget is completely empty and the header is changed into "No file selected". When a main program file is created, it is automatically selected and the text editor is ready for use. +fixed a bug that sometimes when creating a new main program file, the file would be created, but it would not appear in the spec editor.
Re spine-tools/Spine-Toolbox#2099
=> Fix select new file in Tool Spec Editor

spine_items/tool/widgets/tool_spec_optional_widgets.py, tests/tool/widgets/test_PythonToolSpecOptionalWidget.py
Stops reloading kernels when switching between the Basic Console and Jupyter Console radio buttons in Tool Specification Editor.
Re spine-tools/Spine-Toolbox#1809
=> Don't reload kernels if they have already been loaded

requirements.txt, spine_items/tool/widgets/tool_specification_editor_window.py
The icons in Program files and Input & output files -widgets don't overlap with the texts anymore.
Fixes spine-tools/Spine-Toolbox#2160
=> Fix Text and icons overlapping in tool spec editor

spine_items/importer/mvcmodels/mappings_model.py
It used to be that only columns that were not pivoted didn't have their data types changed to floats. Now also ignored columns from Mapping options are excluded from the conversion.
Fixes spine-tools/Spine-Toolbox#2158
=> fix importer pivot forces ignored column data type to float

spine_items/utils.py
Increased the amount of scenario names' characters in generated subdirectories from 15 to 20.
Re spine-tools/Spine-Toolbox#2081
=> Add tooltip warning about long scenario names in db editor

spine_items/tool/tool.py, tests/test_models.py, tests/tool/test_Tool.py
On large projects that have a large amount of files as possible resources for a Tool, checking the Tool's notifications took a long time. Now the checks for duplicate files in resource files and checking if the input file requirements are met are only conducted when either the requirements or resources have changed. The checking of file duplicates has also been made faster.
Re spine-tools/Spine-Toolbox#2083
=> Speed up checking Tools' notifications

setup.cfg
Matches spine-tools/Spine-Toolbox#2194
Fixes spine-tools/Spine-Toolbox#2161 and spine-tools/Spine-Toolbox#2121
=> upgrade pyside to fix Windows 11 crash

spine_items/tool/tool.py, spine_items/tool/utils.py, tests/tool/test_Tool.py
If a ProjectItemResource has a filepath, instead of it being formed every time it is needed, it is now calculated only once. The check for fulfilling required files is now completed once one match is found for every required file.
Re spine-tools/Spine-Toolbox#2083
=> Further speedup Tool's notification check

spine_items/exporter/do_work.py
Sometimes Exporter's `do_work()` fails to create the output directory when the project is stored on OneDrive. This manifests as a Traceback from `FileNotFoundError` which we now catch properly in a `except` block preventing the crash.
Fixes spine-tools/Spine-Toolbox#2211
=> Fix Exporter running indefinitely when outputting to directory on OneDrive

spine_items/exporter/widgets/preview_updater.py
Exporter's preview didn't show anything first when turned on. Only after a change was made in the mapping, it updated. The table names for the mappings in the preview were also missing. At least partially caused by a bug in pyside: https://bugreports.qt.io/browse/PYSIDE-2406
Fixes spine-tools/Spine-Toolbox#2233
=> Fix Exporter preview

spine_items/exporter/commands.py
Due to some pyside changes disabling a mapping from an Exporter specification editor was impossible, the checkbox was always checked.
Fixes spine-tools/Spine-Toolbox#2236
=> Fix Exporter mappings not disabling

spine_items/data_transformer/ui/class_renamer_editor.py, spine_items/data_transformer/ui/class_renamer_editor.ui, spine_items/data_transformer/ui/parameter_renamer_editor.py, spine_items/data_transformer/ui/parameter_renamer_editor.ui, spine_items/data_transformer/ui/value_transformer_editor.py, spine_items/data_transformer/ui/value_transformer_editor.ui, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui
Disabled fully collapsing widgets by setting every QSplitters childrenCollapsible property to false.
Fixes spine-tools/Spine-Toolbox#2167
=> Fix fully collapsable widgets

spine_items/exporter/widgets/specification_editor_window.py
Spinbox arrows in exporter spec editor no longer crash toolbox
Fixes spine-tools/Spine-Toolbox#2235
=> Fix Toolbox crashing when clicking Exporter spinbox arrows

spine_items/tool/tool_instance.py, spine_items/tool/widgets/options_widgets.py, spine_items/utils.py, tests/tool/test_Tool.py
This PR resurrects Julia sysimage creation.
Accompanying PRs:
spine-tools/spine-engine#111
spine-tools/Spine-Toolbox#2246
Fixes spine-tools/Spine-Toolbox#1225
=> Fix Julia sysimage creation

.github/workflows/run_unit_tests.yml
`spinetoolbox` package gets installed along other `spine_items` requirements when we run GitHub actions. Installation of `spinetoolbox`, however, requires that the latest version of `spine_items` is available on PyPI. There is a corner case when the version does not exist: right before we publish new versions to PyPI. This prevents GitHub actions from succeeding.
Instead of allowing `spinetoolbox` to install another "shadow" `spine_items` package in `site-packages`, we now install the `spine-items` repository as editable package with `pip` (without installing its dependencies at this point) before we actually install `requirements.txt`. Since, at this point, `pip` finds `spine_items` already installed, it happily installs `spinetoolbox` as well.
=> Fix GitHub actions after version bump and tagging

spine_items/importer/mvcmodels/mappings_model.py, spine_items/importer/widgets/import_sources.py
Now when an importer spec is modified to have a column reference that is out of range for the source data, an error is shown. If such importer spec is executed an error will also be thrown and logged.
Fixes spine-tools/Spine-Toolbox#2333
=> Fix importer fewer columns than expected Traceback

spine_items/utils.py
Some database dialects that are not supported by spinedb_api but are supported by SqlAlchemy did not work at all as Data connection URLs. This PR alleviates the situation.
Re spine-tools/Spine-Toolbox#2329
=> Fix previously unsupported database dialects in Data connection

spine_items/database_validation.py, tests/test_database_validation.py
Data connection should no longer cause Tracebacks if the user tries to enter an invalid sqlite URL.
Fixes spine-tools/Spine-Toolbox#2371
=> Issue 2371 database validation URL

requirements.txt, spine_items/tool/tool_instance.py, spine_items/tool/tool_specifications.py, spine_items/tool/utils.py, tests/tool/test_tool_instance.py, tests/tool/test_tool_specifications.py, tests/tool/test_utils.py
This PR cleans up ToolInstance classes and adapts ExecutionManager instantiations to changes on spine-engine's PR https://github.com/spine-tools/spine-engine/pull/118.
Re spine-tools/spine-engine#117
=> Adapt ToolInstances to ExecutionManager changes

spine_items/data_connection/data_connection.py, spine_items/data_connection/widgets/custom_menus.py, spine_items/data_store/data_store.py, spine_items/database_validation.py
Now when a db connection is not valid the reference is colored to red just as the file references are to
indicate that there is a problem. By refreshing the connection can be checked again.
Fixes spine-tools/Spine-Toolbox#2375
=> Data connection marks invalid db refs red

spine_items/data_connection/data_connection.py, spine_items/database_validation.py, spine_items/importer/importer.py, spine_items/importer/importer_factory.py, spine_items/importer/widgets/import_editor_window.py, spine_items/models.py
- Data connection's database URL validation was broken for SQLite databases and tried to connect to remote databases without credentials
- Importer did not properly recognize database URLs as valid data source when double-clicking the icon
Fixes spine-tools/Spine-Toolbox#2329
=> Fix issues with remote (non-Spine) databases

spine_items/data_connection/data_connection.py, spine_items/data_connection/executable_item.py, spine_items/data_connection/output_resources.py, spine_items/data_connection/utils.py, spine_items/data_store/data_store.py, spine_items/database_validation.py, spine_items/importer/importer.py, spine_items/importer/importer_factory.py, spine_items/importer/widgets/import_editor_window.py, spine_items/models.py, spine_items/utils.py, tests/data_connection/test_DataConnection.py, tests/data_connection/test_DataConnectionExecutable.py, tests/data_connection/test_output_resources.py, tests/importer/widgets/test_import_editor_window.py, tests/test_database_validation.py, tests/tool/test_tool_instance.py, tests/tool/test_tool_specifications.py
This PR fixes a number of issues that prevented database URLs (other than SQLite) from being used as references in Data Connection and Source preview in Importer specification editor.
Fixes spine-tools/Spine-Toolbox#2329
=> Fix usage of database URLs in Data connection, Importer

spine_items/importer/connection_manager.py, spine_items/importer/ui/import_editor_window.py, spine_items/importer/ui/import_editor_window.ui, spine_items/importer/widgets/import_editor_window.py, spine_items/importer/widgets/import_sources.py, tests/importer/widgets/test_ImportPreview_Window.py, tests/importer/widgets/test_import_editor_window.py
We now remove username and password from the source URL before showing it in Importer Specification editor.
Also, the source combo box has been replaced by a text field which makes more sense and simplifies code.
Resolves spine-tools/Spine-Toolbox#2429
=> Hide credentials from Importer's source URL widget

spine_items/data_store/data_store.py, spine_items/utils.py, tests/test_utils.py
This PR fixes a bug where database credentials were always stored under "None" instead of sanitized database URL.
Re spine-tools/Spine-Toolbox#2329
=> Fix storing/loading database references for Data connections

spine_items/data_store/data_store.py
The option to rename a Data Store is disabled from the action menu while the Data Store is open.
Fixes spine-tools/Spine-Toolbox#2458
=> Disable renaming a Data Store while it is open in an editor

spine_items/tool/widgets/options_widgets.py
Fixes two bugs in sysimage creation:
- Call Pkg.add() for all entries in loaded_modules.txt but catch a Pkg.Types.PkgError exception so that modules are skipped and only actual packages are installed. This fixes sysimage creation for Julia 1.9+ which introduced Extensions.
- Do not Pkg.add() packages that have been installed already. This fixes sysimage creation for development packages.
Re spine-tools/Spine-Toolbox#2451
=> Fix creating system images

spine_items/exporter/widgets/specification_editor_window.py
Fixes spine-tools/Spine-Toolbox#2530
=> Fix initial entity position in exporter mappings

requirements.txt, spine_items/data_connection/data_connection_icon.py, spine_items/data_connection/widgets/data_connection_properties_widget.py, spine_items/importer/widgets/importer_properties_widget.py, tests/data_connection/test_DataConnection.py, tests/data_store/test_dataStore.py, tests/data_transformer/test_DataTransformer.py, tests/exporter/test_Exporter.py, tests/importer/test_Importer.py, tests/tool/test_Tool.py, tests/view/test_View.py
This PR removes spine-items's dependency from Toolbox's Project dock widget.
Fixes spine-tools/Spine-Toolbox#2560
=> Fix code relying on Project dock widget

spine_items/__init__.py
File-based scanning of the items package does not work when Spine Toolbox is bundled by e.g. PyInstaller as the `.py` files do not exist in the bundle. This PR enables the users of `spine_items` to discover item factories etc. without the need for touching the file system. Further, it gives the responsibility which items should be discoverable from outside to `spine_items` itself.
No related issue
=> Expose entry points to items in package root

spine_items/importer/mvcmodels/mappings_model.py, tests/importer/mvcmodels/test_mappings_model.py
'Select all' can now be unchecked even when there is no source tables. Also, new tables created in sourceless modes are born as checked/unchecked depending on 'Select all'.
Fixes spine-tools/Spine-Toolbox#2627
=> Make Importer's Select all check box more intuitive

spine_items/exporter/mvcmodels/mapping_editor_table_model.py, spine_items/importer/mvcmodels/mappings_model.py, tests/importer/mvcmodels/test_mappings_model.py
Use rich text in tool tips so Qt can wrap the text.
Re spine-tools/Spine-Toolbox#2542
=> Improve tool tips

spine_items/importer/widgets/import_editor_window.py
Fixes spine-tools/Spine-Toolbox#2661
=> Fix Importer Spec Editor window layout

spine_items/importer/mvcmodels/mappings_model.py, tests/importer/mvcmodels/test_mappings_model.py
Importer was using legacy functionality in `spinedb_api` to get blank mappings when user changed the mapping type. This did not work e.g. with Entity group mappings since those did not exist in pre-0.7 world.
Fixes spine-tools/Spine-Toolbox#2662
spine-tools/Spine-Toolbox# (issue)
=> Fix changing Importer's mapping type

spine_items/importer/flattened_mappings.py
Re spine-tools/Spine-Toolbox#2522
=> Drop imports from deprecated distutils

pyproject.toml, requirements.txt
This PR updates `spine-items` to allow using PySide6 6.6.
Re spine-tools/Spine-Toolbox#2345
=> Support PySide 6.6

.github/workflows/run_unit_tests.yml, pyproject.toml, requirements.txt
- Instead, add a step to Github test runner action to install coverage
Re spine-tools/Spine-Toolbox#2268
=> Don't install coverage while installing the package

.github/workflows/run_unit_tests.yml, README.md, dev-requirements.txt, pyproject.toml
This PR removes the Python version restriction < 3.12 from Spine-Items.
Re spine-tools/Spine-Toolbox#2522
=> Lift Python version upper limit

requirements.txt, spine_items/importer/flattened_mappings.py, spine_items/importer/mvcmodels/mappings_model.py, spine_items/importer/widgets/import_mappings.py, tests/importer/mvcmodels/test_mappings_model.py
https://github.com/spine-tools/Spine-Database-API/pull/423
Re spine-tools/Spine-Toolbox#2223
=> Issue 2223 mapping name importer source

spine_items/tool/widgets/tool_specification_editor_window.py, tests/tool/widgets/test_toolSpecificationEditorWindow.py
Fixes spine-tools/Spine-Toolbox#2890
=> Fix traceback caused by tool main file renaming

.pre-commit-config.yaml, pyproject.toml
Now both isort and black are included in the pre-commit hooks.
Fixes spine-tools/Spine-Toolbox#2897
=> Add pre-commit hooks

spine_items/exporter/preview_table_writer.py, tests/exporter/test_output_channel.py, tests/exporter/test_preview_table_writer.py, tests/exporter/test_specification.py, tests/exporter/test_utils.py, tests/exporter/widgets/test_preview_updater.py, tests/importer/widgets/test_import_sources.py
`float_` is no more in `numpy` 2.0.
=> Fix numpy 2.0 compatibility issue in Exporter

spine_items/exporter/ui/value_type_filter_editor.py, spine_items/exporter/ui/value_type_filter_editor.ui, spine_items/exporter/widgets/specification_editor_window.py, spine_items/importer/ui/import_editor_window.py
`single_value` value type does not exist anymore. Instead, we have `float`, `bool` and `str`.
=> Fix regular expression hints in Exporter

spine_items/exporter/widgets/specification_editor_window.py
It is no longer possible to set Entity dimensions to zero in Exporter Specification editor when mapping type is
"Entity class with dimension parameter".
=> Prevent impossible settings when exporting entity classes with dimension parameter

spine_items/exporter/ui/specification_editor.py, spine_items/exporter/ui/specification_editor.ui, spine_items/exporter/widgets/preview_updater.py, tests/exporter/widgets/test_preview_updater.py, tests/importer/widgets/test_import_mapping_options.py, tests/mock_helpers.py
This PR makes Exporter's Specification editor run much smoother while updating the preview tables. Since they do not freeze the UI anymore, previews are enable by default now. If we experience unresponsive UI again, we can change the default back to disabled.
Fixes spine-tools/Spine-Toolbox#2898
=> Make Exporter's preview a smoother experience

spine_items/data_store/data_store.py
This fixes wonky behavior when project was saved and closed without properly defining a Data Store's URL.
Fixes spine-tools/Spine-Toolbox#2915
=> Fix constructing a Data Store with incomplete URL

spine_items/tool/ui/tool_specification_form.py, spine_items/tool/ui/tool_specification_form.ui
Users tend to accidentally close the editor dock once they finish editing.
Re spine-tools/Spine-Toolbox#2963
=> Make Tool spec editor's script editor dock non-closable

spine_items/importer/commands.py, spine_items/importer/flattened_mappings.py, spine_items/importer/mvcmodels/mappings_model.py, spine_items/importer/mvcmodels/source_data_table_model.py, spine_items/importer/ui/import_editor_window.py, spine_items/importer/ui/import_editor_window.ui, spine_items/importer/widgets/import_mapping_options.py, tests/importer/mvcmodels/test_mappings_model.py, tests/importer/test_flattened_mappings.py
This PR fixes minor issues in Importer:
- If the last mapping component is positioned on Row (or header), we do not mark the component as "Pivoted" because it prevents modifying the component anymore.
- Removed the option to enable "before alternative" scenario alternative mappings, also from Exporter. Practically no-one uses this pretty esoteric mapping
- Fix some cases where the Source table colors were off.
Re spine-tools/Spine-Toolbox#2962
=> Fix issues in Importer specification editor

spine_items/data_store/commands.py, spine_items/data_store/widgets/data_store_properties_widget.py, spine_items/widgets.py, tests/data_store/test_commands.py, tests/data_store/test_dataStore.py, tests/test_widgets.py
sqlite is by far the number one choice.
Also fixed some bugs in undo action and the URL widget.
Implements spine-tools/Spine-Toolbox#2968
=> Make sqlite readily selected in empty Data store properties

spine_items/importer/ui/import_editor_window.py, spine_items/tool/ui/tool_specification_form.py, spine_items/ui/url_selector_dialog.py, spine_items/ui/url_selector_dialog.ui, spine_items/ui/url_selector_widget.py, spine_items/ui/url_selector_widget.ui, spine_items/widgets.py
- No-one uses MSSQL at least to my knowledge
- Getting this to work would have required adding `pyodbc` module as dependency
- The DSN information wasn't used anywhere so getting the feature to work would have required implementation effort.
=> Remove support for MSSQL dialect

spine_items/data_store/data_store.py, spine_items/utils.py, spine_items/view/view.py, tests/data_store/test_DataStoreExecutable.py, tests/data_store/test_dataStore.py, tests/exporter/test_utils.py, tests/merger/test_MergerExecutable.py
Data stores are no longer responsible of Database editor's tab names. They merely register their names as candidates for database display names but it is up to Toolbox what it chooses to do with the information. This simplifies code and responsibilities in `spine_items`.
=> Use the new DB editor facilities in Toolbox

spine_items/tool/widgets/tool_specification_editor_window.py
Fixes spine-tools/Spine-Toolbox#3006
=> Fix random segfault when adding source files to Tool specification editor

spine_items/data_connection/ui/data_connection_properties.py, spine_items/data_connection/ui/data_connection_properties.ui, spine_items/data_store/ui/data_store_properties.py, spine_items/data_store/ui/data_store_properties.ui, spine_items/data_transformer/ui/data_transformer_properties.py, spine_items/data_transformer/ui/data_transformer_properties.ui, spine_items/exporter/ui/exporter_properties.py, spine_items/exporter/ui/exporter_properties.ui, spine_items/exporter/ui/value_type_filter_editor.py, spine_items/importer/ui/import_editor_window.py, spine_items/importer/ui/importer_properties.py, spine_items/importer/ui/importer_properties.ui, spine_items/merger/ui/merger_properties.py, spine_items/merger/ui/merger_properties.ui, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, spine_items/tool/ui/tool_specification_form.py, spine_items/view/ui/view_properties.py, spine_items/view/ui/view_properties.ui, tests/data_connection/test_DataConnection.py, tests/importer/test_importer_icon.py, tests/merger/test_merger_icon.py, tests/mock_helpers.py, tests/tool/test_tool_instance.py, tests/tool/widgets/test_toolSpecificationEditorWindow.py
Fixes spine-tools/Spine-Toolbox#3012 partly. A second PR is needed on Toolbox side.
=> Add QScrollAreas to Project Item Properties widgets

spine_items/data_connection/ui/data_connection_properties.py, spine_items/data_connection/ui/data_connection_properties.ui, spine_items/data_store/ui/data_store_properties.py, spine_items/data_store/ui/data_store_properties.ui, spine_items/data_transformer/ui/data_transformer_properties.py, spine_items/data_transformer/ui/data_transformer_properties.ui, spine_items/exporter/ui/exporter_properties.py, spine_items/exporter/ui/exporter_properties.ui, spine_items/importer/ui/importer_properties.py, spine_items/importer/ui/importer_properties.ui, spine_items/merger/ui/merger_properties.py, spine_items/merger/ui/merger_properties.ui, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, spine_items/view/ui/view_properties.py, spine_items/view/ui/view_properties.ui
Add stylesheets to properties widgets scroll areas to make scroll area backgrounds transparent.
Fixes spine-tools/Spine-Toolbox#3012
=> Fix Color properties widget setting

requirements.txt, spine_items/commands.py, spine_items/tool/tool.py, spine_items/tool/tool_instance.py, spine_items/tool/tool_specifications.py, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, spine_items/tool/widgets/tool_specification_editor_window.py
Fixes https://github.com/spine-tools/Spine-Toolbox/issues/3020
=> Allows to have main program file in a directory.

spine_items/tool/widgets/tool_specification_editor_window.py
Fixes spine-tools/Spine-Toolbox#2961
=> Add file type filters to QFileDialogs based on selected tool type

tests/tool/test_ToolExecutable.py
Re spine-tools/Spine-Toolbox#2986
=> Fix unit test for Python 3.13

spine_items/importer/widgets/import_editor_window.py, tests/data_transformer/test_DataTransformer.py, tests/exporter/test_Exporter.py, tests/exporter/widgets/test_specification_editor_window.py, tests/importer/test_Importer.py, tests/importer/widgets/test_ImportPreview_Window.py, tests/importer/widgets/test_import_editor_window.py
- If souce type stored in the mapping clashes with source type, user now gets a warning before seeing the source selector.
- In the above case and if user chooses a different source type to what is defined in the mapping, the undo stack is marked as dirty so it is actually possible to save the specification afterwards.
- The source selector dialog is now shown only after the specification window is shown. This enables showing correct icon in the dialog as well.
No associated issue
=> Fix issues with Importer's source selector dialog

spine_items/data_store/data_store.py, spine_items/data_transformer/widgets/class_tree_widget.py, spine_items/data_transformer/widgets/parameter_tree_widget.py, spine_items/utils.py, tests/exporter/widgets/test_specification_editor_window.py
Migrate from SQLAlchemy 1.3 to 1.4
Re spine-tools/Spine-Database-API#121
=> Migrate to SQLAlchemy 1.4

spine_items/data_store/data_store.py
This fixes a bug where Data Store's SQLite path was pointing to the previous directory after the item was renamed if the database file was in the item's data directory.
Fixes spine-tools/Spine-Toolbox#3055
=> Fix Data Store renaming

spine_items/importer/do_work.py
Not finding the table of a fixed target mapping does not anymore cause Importer to fail when "Cancel on error" is not set.
Re spine-tools/Spine-Database-API#506
=> Fix cancelling on error in Importer

spine_items/importer/importer.py, spine_items/models.py
This PR adds a warning notification on Importers on Design View, which do not have any source items selected in the Importer Properties.
Fixes spine-tools/Spine-Toolbox#3061
=> Add a notification to Importer

spine_items/importer/do_work.py
Otherwise writing the file may Traceback if the error messages contain special characters.
=> Use UTF-8 encofing for Importer's log file

spine_items/data_store/data_store.py
Data stores do not treat databases with cancelled/failed upgrades as valid.
Fixes spine-tools/Spine-Toolbox#3067
=> Make cancelled/failed database upgrade an error

spine_items/commands.py, spine_items/tool/executable_item.py, spine_items/tool/tool.py, spine_items/tool/ui/executable_cmd_exec_options.py, spine_items/tool/ui/julia_kernel_spec_options.py, spine_items/tool/ui/julia_options.py, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, tests/tool/test_Tool.py
This PR adds a line edit next to the Results... button in Tool Properties, where one can change the results directory.
In addition, Tools should not make any empty result directories anymore!
Fixes spine-tools/Spine-Toolbox#1994
=> Support changing Tool results directory

dev-requirements.txt, tests/data_store/test_dataStore.py
Add `pytest` to `dev-requirements.txt`. `pytest` can now be used in place of `unittest`.
> [!IMPORTANT]  
> Please let me know if you would like changes to documentation or release notes as well. Should we switch the CI to `pytest`?
Fixes #262
To keep the `pytest` compatibility, I would suggest following the [pytest naming conventions](https://docs.pytest.org/en/stable/explanation/goodpractices.html#conventions-for-python-test-discovery) for tests. For `spine-items` we are doing this already. Brief summary:
- In the `tests` directory, files are named `test_*.py` or `*_test.py`.
- Within those files, `test` prefixed test functions or methods outside of class, and `test` prefixed test functions or methods inside `Test` prefixed test classes (without an `__init__` method) are run.
Rule of …
=> Enable Pytest

spine_items/merger/do_work.py
Merger now catches ´spinedb_api´ errors when committing merged data.
Re spine-tools/Spine-Toolbox#3125
=> Better error handling for Merger

spine_items/data_store/data_store.py, spine_items/utils.py, tests/data_store/test_DataStoreExecutable.py, tests/data_store/test_dataStore.py, tests/merger/test_MergerExecutable.py
We should case-normalize paths only when doing comparisons. *NIX paths are case-sensitive, so we must store them as-is in project.json.
Fixes spine-tools/Spine-Toolbox#3038
=> Don't store case-normalized SQLite paths in project.json
