tests/importer/test_ImporterExecutable.py, tests/merger/test_MergerExecutable.py
=> Start and shutdown db server managers as needed for tests

tests/importer/test_ImporterExecutable.py, tests/merger/test_MergerExecutable.py
=> Use the new queue db server manager

spine_items/view/view.py
=> Import FetchParent from the right place

setup.cfg, spine_items/version.py
Published items in PyPI
Fixes Spine-project/Spine-Toolbox#1888
=> Bump version

spine_items/importer/widgets/import_mapping_options.py, tests/importer/widgets/test_import_mapping_options.py
Fixes Spine-project/Spine-Toolbox#1902
=> Fix Importer's Repeat time series check box

spine_items/data_connection/data_connection.py, tests/data_connection/test_DataConnection.py
Fixes Spine-project/Spine-Toolbox#1908
=> Fix removing file references with delete key and add test

spine_items/tool/executable_item.py
- Make work directory if it's missing after checking input/output files
Fixes spine-tools/Spine-Toolbox#2025
=> Fix executing Executable Tool Specs in work directory

spine_items/database_validation.py, tests/test_database_validation.py
Re spine-tools/Spine-Toolbox#1668
=> Fix warning in database validation

spine_items/exporter/executable_item.py
Fixes  spine-tools/Spine-Toolbox#2043
=> Fix Traceback in Exporter

spine_items/db_writer_item_base.py, spine_items/importer/importer.py, spine_items/merger/merger.py, spine_items/tool/tool.py
=> Check write index and show exclamation points if needed

spine_items/data_connection/data_connection.py
Instead of trying once to find the files, try it five times in one second intervals.
Fixes spine-tools/Spine-Toolbox#2079
=> Fix disappearing files in Data connection

spine_items/data_store/executable_item.py
See master PR spine-tools/spine-engine#100
Re spine-tools/spine-engine#99
=> Mark Data Store as end point for filtered execution

tests/merger/test_MergerExecutable.py
A unit test got broken due to changes in spine-engine.
Re spine-tools/spine-engine#99
=> Fix unit tests

spine_items/tool/widgets/tool_specification_editor_window.py
This fixes a bunch of issues with the program files tree in Tool specification editor including spurious notifications that a program file is not valid and numerous Tracebacks when adding additional program files without a main program file.
Fixes spine-tools/Spine-Toolbox#2175
=> Fix issues with Program files dock in Tool specification editor

spine_items/tool/ui/python_kernel_spec_options.py, spine_items/tool/ui/tool_specification_form.py, spine_items/tool/ui/tool_specification_form.ui, spine_items/tool/widgets/tool_specification_editor_window.py
Somehow these changes didn't make it to PR #135
Fixes spine-tools/Spine-Toolbox#2175
=> Follow up to fixing Tool specification editor issues

spine_items/tool/commands.py, spine_items/tool/executable_item.py, spine_items/tool/tool.py, spine_items/tool/ui/tool_properties.py, spine_items/tool/ui/tool_properties.ui, spine_items/tool/ui/tool_specification_form.py, tests/tool/test_ToolExecutable.py
=> Implement logging tool output to file

spine_items/tool/executable_item.py, tests/tool/test_ToolExecutable.py
=> Write header with info in log files

pyproject.toml
Fixes line endings in project.toml
=> Fix project.toml

spine_items/utils.py
This PR reimplements the changes from PR #161 for the 0.7 branch
Re spine-tools/Spine-Toolbox#2329
=> Make all database dialects work

spine_items/view/view.py
This PR fixes deserialization of View item.
See also spine-tools/Spine-Toolbox#2357 which fixes plotting in Toolbox side.
Fixes spine-tools/Spine-Toolbox#2356
=> Fix View deserialization

spine_items/importer/widgets/import_editor_window.py
Fixed typo
Fixes spine-tools/Spine-Toolbox#2372
=> Fix opening URL selector in importer causes Traceback

spine_items/importer/executable_item.py
Fixed imports
Fixes spine-tools/Spine-Toolbox#2427
=> Fix not able to open Toolbox due to Traceback from imports

spine_items/tool/executable_item.py, spine_items/tool/utils.py, tests/tool/test_tool_instance.py, tests/tool/test_utils.py
Fixes spine-tools/Spine-Toolbox#2460
=> Fix finding Julia from PATH

spine_items/exporter/widgets/preview_updater.py, spine_items/importer/widgets/multi_checkable_list_view.py
Inspired by spine-tools/Spine-Toolbox#2581
=> Fix some check boxes in Exporter, Importer

spine_items/__init__.py
=> Fix a bug that prevented the creation of new Data transformer specifications

spine_items/tool/utils.py, spine_items/tool/widgets/tool_spec_optional_widgets.py
Re spine-tools/Spine-Toolbox#2702
=> Fix bug in Julia Tool Specs not using global Julia environment

requirements.txt, spine_items/db_writer_item_base.py, spine_items/exporter/exporter.py, spine_items/tool/tool.py, tests/data_store/test_dataStore.py
Re spine-tools/Spine-Toolbox#2523
=> Spine Items changes related to ditching Dagster

pyproject.toml, spine_items/exporter/executable_item.py, spine_items/exporter/widgets/preview_updater.py, spine_items/tool/tool.py, spine_items/tool/widgets/tool_specification_editor_window.py
This PR formats the code with black version 24.4.2.
No functional changes whatsoever.
Re spine-tools/Spine-Toolbox#2733
=> Reformat source code with latest Black

spine_items/exporter/mvcmodels/mapping_editor_table_model.py, spine_items/exporter/widgets/specification_editor_window.py, spine_items/importer/flattened_mappings.py, spine_items/importer/mvcmodels/mappings_model.py
The mapping is now gone from spinedb_api
Re spine-tools/Spine-Toolbox#2738
=> Remove code related to scenario active flag import/export

.github/workflows/run_unit_tests.yml
Re spine-tools/Spine-Toolbox#2642
=> Enable Pip caching when running GitHub Actions

requirements.txt, spine_items/tool/tool_instance.py, spine_items/tool/utils.py, tests/tool/test_tool_instance.py, tests/tool/test_utils.py
Re spine-tools/Spine-Toolbox#2824
=> Use new util function to find kernel specs

.github/workflows/run_unit_tests.yml, README.md, pyproject.toml
Re spine-tools/Spine-Toolbox#2904
=> Require Python 3.9

spine_items/importer/flattened_mappings.py, spine_items/importer/mvcmodels/source_data_table_model.py
Bugs found while hunting another bug that turned out to be in `spinedb_api` side.
No associated issues.
=> Fix a few minor bugs in Importer

.github/workflows/run_unit_tests.yml, README.md, pyproject.toml
Re spine-tools/Spine-Toolbox#2986
=> Support Python 3.13

spine_items/animations.py, spine_items/importer/widgets/table_view_with_button_header.py
Re spine-tools/Spine-Toolbox#1265
=> Fix icons on MacOS

spine_items/exporter/widgets/preview_updater.py, tests/exporter/widgets/test_preview_updater.py
This PR fixes a deadlock in Exporter preview.
=> Fix deadlock in Exporter's preview

tests/mock_helpers.py
This PR makes spine-items tests consistent with toolbox tests.
Fixes spine-tools/Spine-Toolbox#3110
=> Use default QSettings when running tests

.github/workflows/run_unit_tests.yml, pylintrc, pyproject.toml
Re spine-tools/Spine-Toolbox#3038
=> Drop Python 3.9 support
